In [1]:
#Q1
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

temperature = temperature + 2

fahrenheit = (9/5) * temperature + 32

above_32 = temperature[temperature > 32]

count = np.sum(temperature > 32)

print("Corrected temperature:", temperature)
print("Temperature in Fahrenheit:", fahrenheit)
print("Readings greater than 32°C:", above_32)
print("Number of readings exceeding 32°C:", count)

Corrected temperature: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


In [2]:
#2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))
print("Total steps for each day:", np.sum(steps, axis=0))
print("Total steps for each user:", np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum: (np.int64(3), np.int64(2))


In [3]:
#Q3
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original:", original)
print("Subset:", subset)

copied_array = original[1:5].copy()
copied_array[0] = 500

print("Original:", original)
print("Copied array:", copied_array)

arr = np.arange(1, 13).reshape(3, 4)

print("3 x 4 matrix:")
print(arr)

print("First row:", arr[0])
print("Last row:", arr[-1])
print("Second column:", arr[:, 1])
print("Rows 1-2 and columns 2-3:")
print(arr[0:2, 1:3])

flattened = arr.flatten()
raveled = arr.ravel()

print("Flatten:", flattened)
print("Ravel:", raveled)

raveled[0] = 100
print("After modifying ravel:")
print("Original:", arr)
print("Ravel:", raveled)

flattened[1] = 200
print("After modifying flatten:")
print("Original:", arr)
print("Flatten:", flattened)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After modifying ravel:
Original: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Ravel: [100   2   3   4   5   6   7   8   9  10  11  12]
After modifying flatten:
Original: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flatten: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [4]:
#Q4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape:", X.shape)
print("Dimensions:", X.ndim)

print("X.T:")
print(X.T)

XT_X = X.T @ X
print("X.T @ X:")
print(XT_X)

inverse = np.linalg.inv(XT_X)
print("Inverse:")
print(inverse)

beta = inverse @ X.T @ y
print("Coefficients:", beta)

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape: (4, 3)
Dimensions: 2
X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
Coefficients: [-0.15921454  0.14083853 10.06302242]
Predicted assistance score: 75.27862544779117
