In [1]:
#Q1
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# a) Add 2 to every element
print("After adding 2:", arr + 2)

# b) Multiply every element by 3
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [3]:
#q2(a)
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reverse_arr = arr[::-1]

print(reverse_arr)

[5 4 6 3 2 1]


In [4]:
#2(b)
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(x == most_frequent)

print("Most frequent value:", most_frequent)
print("Indices:", indices[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [6]:
#Q3
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [8]:
#Q4
import numpy as np


your_name = np.linspace(10, 100, 25)

print("Array:", your_name)

print("Dimensions:", your_name.ndim)

print("Shape:", your_name.shape)


print("Total elements:", your_name.size)


print("Data type:", your_name.dtype)

print("Total bytes:", your_name.nbytes)


transpose_array = your_name.reshape(25, 1)

print("Transpose using reshape():")
print(transpose_array)


print("Transpose using T:")
print(your_name.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
#Q5
import numpy as np

ucs420_your_name = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean:", np.mean(ucs420_your_name))
print("Median:", np.median(ucs420_your_name))
print("Maximum:", np.max(ucs420_your_name))
print("Minimum:", np.min(ucs420_your_name))
print("Unique elements:", np.unique(ucs420_your_name))

reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)
print("Reshaped array:")
print(reshaped_ucs420_your_name)

resized_ucs420_your_name = np.resize(ucs420_your_name, (2, 3))
print("Resized array:")
print(resized_ucs420_your_name)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
